server:
  port: 8091

spring:
  application:
    name: POST-SERVICE

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA.URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true



jwt:
  secret:
    key:  753778214125442A472D4B6150645367566B59703373367639792F423F452848
  access:
    expiry: 30000000
  refresh:
    expiry: 30000000
