server:
  port: 8091

spring:
  application:
    name: POST-SERVICE
  datasource:
    username: postgres
    password: 1402
    url: jdbc:postgresql://localhost:5433/post_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA.URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true


jwt:
  secret:
    key:  753778214125442A472D4B6150645367566B59703373367639792F423F452848


services:
  user-service-url: http://USER-SERVICE/user